# Interventions
FIELDNAME_FRAMES = "frames"
FIELDNAME_VIDEO_PATH = "video_path"
FIELDNAME_TOKENS = "tokens"
FIELDNAME_TOKENS_PATHO = "patho"
FIELDNAME_TOKENS_REPORT = "report"
FIELDNAME_EXTERNAL_ID = "_id_michael"
FIELDNAME_LABELS_FRAMES = "labels_frames"
FIELDNAME_INTERVENTION_TYPE = "intervention_type"
FIELDNAME_FREEZES = "freezes"
FIELDNAME_INTERVENTION_DATE = "intervention_date"
FIELDNAME_VIDEO_METADATA = "metadata"
FIELDNAME_FPS = "fps"
FIELDNAME_FRAMES_TOTAL = "frames_total"
FIELDNAME_PATHO_RAW = "patho_raw"
FIELDNAME_REPORT_RAW = "report_raw"

# Images
FIELDNAME_INTERVENTION_ID = "intervention_id"
FIELDNAME_LABELS = "labels_new"
FIELDNAME_PREDICTIONS = "predictions"
FIELDNAME_IMAGE_PATH = "path"
FIELDNAME_FRAME_NUMBER = "n"
FIELDNAME_LABELS_VALIDATED = "labels_validated"
FIELDNAME_LABELS_UNCLEAR = "labels_unclear"
FIELDNAME_IMAGE_TYPE = "image_type"
LABEL_UNCLEAR = "unclear"

# Shared
FIELDNAME_ORIGIN = "origin"
FIELDNAME_VIDEO_KEY = "video_key"

# AI
FIELDNAME_AI_VERSION = "version"
FIELDNAME_IMAGE_SCALING = "image_scaling"
FIELDNAME_PREDICTION_VALUE = "value"

# OTHER STRING CONSTANTS
IMAGETYPE_FRAME = "frame"
IMAGETYPE_FREEZE = "freeze"